### ISSUE TITLE
mod_encrypt parameters need to not conflict with mod_fastcgi

### ISSUE THREAD

**Issue by dmgrimal** [GiorgioRegni/mod_encrypt#1]
When trying to use both mod_fastcgi and mod_encrypt on the same instance of apache, the FastCgiExternalServer parameters conflict.  In order to get both modules to load and work at the same time, the mod_encrypt module needs to use a different parameter. 

To work around this, I changed this line in mod_encrypt.c

<code> 
  AP_INIT_RAW_ARGS("FastCgiExternalServer", fcgi_config_new_external_server, NULL, RSRC_CONF, NULL),
</code>

to 

<code>
  AP_INIT_RAW_ARGS("FastCgiEncExternalServer", fcgi_config_new_external_server, NULL, RSRC_CONF, NULL),
</code>

**Comment by BazeIlijoskki** [comment]
I modified some parameters to avoid conflict.
FastCgiExternalServer -> FastCgiEncExternalServer 
FastCgiMemcachedServer -> FastCgiEncMemcachedServer 
FastCgiEncrypt -> FastCgiEncEncrypt
FastCgiDecrypt -> FastCgiEncDecrypt
FastCgiUserName -> FastCgiEncUserName
FastCgiPassword -> FastCgiEncPassword
FastCgiLogpath -> FastCgiEncLogpath

**Comment by dmgrimal** [comment]
New settings work.  Thanks.
