### ISSUE TITLE
After mod_encrypt version update, encrypt module is down

### ISSUE THREAD

**Issue by sumantmanda** [GiorgioRegni/mod_encrypt#11]
After Dan Gramaldi upgraded the encrypt module we couldnt bring the encrypt module work.

Ive tried reboot and restart of httpd, we see below error in encrypt.log

tail -f /var/log/httpd/encrypt.log

2015-11-17 17:18:22,208 [ERROR]  FastCGIENC: access for server (uid 48, gid 48) failed: execute not allowed by owner

**Comment by BazeIlijoskki** [comment]
Fixed.
