### ISSUE TITLE
httpd crash often

### ISSUE THREAD

**Issue by sumantmanda** [GiorgioRegni/mod_encrypt#12]
Issue: All Uploads, Downloads and Deletes of Objects are failing with 500 errors.

Observation: httpd crashed.

[root@blf-pp-h01-obj01.blfpp-geo:/var/log/httpd]$ service httpd status
httpd dead but pid file exists

httpd log on 231 box

127.0.0.1 - - [12/Nov/2015:02:12:56 +0000] "PUT /encrypt/arc/35515D7614F027B089F5DE615ED0B34900000350 HTTP/1.0" 500 626 "-" "-"
127.0.0.1 - - [12/Nov/2015:02:13:26 +0000] "HEAD /encrypt/arc/210D44E7744CBD909DA9C7615ED0B34900000350 HTTP/1.0" 500 - "-" "-"

RestClient.log

20151112 01:43:28.730 restclient id=0xc98d950 state="start" method="PUT" server="127.0.0.1:81" url="/encrypt/arc/0A9FAD3B28F468B3B63B2E615ED0B34900000350" request_data_len="5639996"
20151112 01:43:59.000 restclient id=0xc98d950 state="error" server="127.0.0.1:81" status="invalid server" http_code="500"
20151112 01:43:59.000 restclient id=0xc98d950 state="end" method="PUT" server="127.0.0.1:81" url="/encrypt/arc/0A9FAD3B28F468B3B63B2E615ED0B34900000350" request_data_len="5639996" response_data_len="0" status="RESTCLIENT_FAILURE_BADPROTO" http_code="500"
20151112 01:44:18.025 restclient id=0x17a6e0e0 state="start" method="PUT" server="127.0.0.1:81" url="/encrypt/arc/0A9FAD3B28F468B3B63B2E615ED0B34900000350" request_data_len="5639996"
20151112 01:44:49.009 restclient id=0x17a6e0e0 state="error" server="127.0.0.1:81" status="invalid server" http_code="500"
20151112 01:44:49.009 restclient id=0x17a6e0e0 state="end" method="PUT" server="127.0.0.1:81" url="/encrypt/arc/0A9FAD3B28F468B3B63B2E615ED0B34900000350" request_data_len="5639996" response_data_len="0" status="RESTCLIENT_FAILURE_BADPROTO" http_code="500"

HAProxy:
Nov 12 02:18:22 blf-pp-h02-node01.blfpp-geo haproxy[6846]: 10.200.107.205:38521 [12/Nov/2015:02:17:51.443] rs2-local-443~ rs2-local-443/server-1 3/0/0/30561/30564 503 176 - - ---- 1/1/0/0/0 0/0 {testnov11.local.onprem.evault.com|AWS d3915364c2d545e599be17654e9e2761:LFarDhIK5CPsAYLO1TYvh7yQ8uM|||Boto/2.32.1 Python/2.6.6 Linux/2.6.32-504.12.2.el6.x86_64} "HEAD /top-100-selenium-interview-questions-and-answers-2015-1-638.jpg HTTP/1.1"
Nov 12 02:18:22 blf-pp-h02-node01.blfpp-geo haproxy[6846]: 10.200.107.205:38521 [12/Nov/2015:02:18:22.007] rs2-local-443~ rs2-local-443/server-1 792/0/0/17/809 503 176 - - ---- 1/1/0/0/0 0/0 {testnov11.local.onprem.evault.com|AWS d3915364c2d545e599be17654e9e2761:LFarDhIK5CPsAYLO1TYvh7yQ8uM|||Boto/2.32.1 Python/2.6.6 Linux/2.6.32-504.12.2.el6.x86_64} "HEAD /top-100-selenium-interview-questions-and-answers-2015-1-638.jpg HTTP/1.1"
Nov 12 02:18:23 blf-pp-h02-node01.blfpp-geo haproxy[6846]: 10.200.107.205:38521 [12/Nov/2015:02:18:22.816] rs2-local-443~ rs2-local-443/server-1 214/0/0/1/215 503 176 - - ---- 1/1/0/0/0 0/0 {testnov11.local.onprem.evault.com|AWS d3915364c2d545e599be17654e9e2761:LFarDhIK5CPsAYLO1TYvh7yQ8uM|||Boto/2.32.1 Python/2.6.6 Linux/2.6.32-504.12.2.el6.x86_64} "HEAD /top-100-selenium-interview-questions-and-answers-2015-1-638.jpg HTTP/1.1"
Nov 12 02:18:25 blf-pp-h02-node01.blfpp-geo haproxy[6846]: 10.200.107.205:38521 [12/Nov/2015:02:18:23.031] rs2-local-443~ rs2-local-443/server-1 2125/0/1/0/2126 503 176 - - ---- 1/1/0/0/0 0/0 {testnov11.local.onprem.evault.com|AWS d3915364c2d545e599be17654e9e2761:LFarDhIK5CPsAYLO1TYvh7yQ8uM|||Boto/2.32.1 Python/2.6.6 Linux/2.6.32-504.12.2.el6.x86_64} "HEAD /top-100-selenium-interview-questions-and-answers-2015-1-638.jpg HTTP/1.1"

**Comment by mastachand** [comment]
Hey Sumant,

can we have the tail of encrypt.log for this as well, please?
thanks

**Comment by sumantmanda** [comment]
encrypt.log was empty, meaning nothing was going through it. thats why I didnt attach it here.

Thanks

**Comment by BazeIlijoskki** [comment]
Fixed.
