### ISSUE TITLE
mod encrypt should always validate the return master key id with the expected master key id

### ISSUE THREAD

**Issue by sumantmanda** [GiorgioRegni/mod_encrypt#13]
Hi Dan

Any update on this ?

Thanks
Tissa

On Wed, Nov 11, 2015 at 5:59 PM, Sumant Manda <sumant.manda@seagate.com> wrote:
Hi Dan,

This is a confirmation after it was tested. Thanks,

Thanks,
Sumant Manda

On Wed, Nov 11, 2015 at 5:08 PM, Dan Grimaldi <dan.grimaldi@scality.com> wrote:
Hey Tissa,

I will look into this.  Do you know if this has been confirmed on your system or if this is just a suspicion about what is happening?

Cheers,

Dan Grimaldi
TAM North America | Scality
+1 (678) 665 4845 (m) | dan.grimaldi@scality.com
http://www.scality.com | Twitter: @scality

On Wed, Nov 11, 2015 at 1:21 PM, Tissa Senevirathne <tissa.senevirathne@seagate.com> wrote:
Dan

The get data key request payload returns master key id. It is possible for an active data key request, due to timing, the data key returned to have a different master key than the one mode encrypt thought as active master key. This may lead to corruption later when retrieving the data.

Could you please make sure , that mod encrypt is always validate the return master key id with the expected master key id ?

Below are the details of the GET key request and response

Request: 
Type: GET
URL: http://54.175.20.74/data/key/
Header: "Authorization: Token 2c70e2af066719bcdf6b2d9ee12d90d78d691552

Response:
{
    "key_id": "b5cecb0a-1c3d-49b4-a743-9cea636b94d1",
    "master_key_id": "e5101f4c-faa0-45a8-baef-8b50d4a1d6ab",
    "state": "Active",
    "refresh_interval": 60,
    "key_encrypted_base64": "KeczEihrHCy9rzU0f0IWloRt7P7e3vPK+YIJbSGGDCsOVPPr0rgqw5nOfGuoow63"
}

Thanks
Tissa

**Comment by BazeIlijoskki** [comment]
Fixed
