### ISSUE TITLE
Download Object (decrypt ) is returning HTTP 504

### ISSUE THREAD

**Issue by sumantmanda** [GiorgioRegni/mod_encrypt#14]
on 231, I've uploaded a Object and when try to download the object I get HTTP 504 gateway error from UI (Zenith)

**Comment by BazeIlijoskki** [comment]
Please tell me the detailed operation and logs. Thanks.

**Comment by BazeIlijoskki** [comment]
There is a confusion in check the length of usermd parameter.
I uploaded 1.0.0-6 version into github.
Please test with 1.0.0-6 again.

Thanks,
Baze

**Comment by BazeIlijoskki** [comment]
Hi

I created new version 1.0.0-7 for the safety of encryption module.
Please continue the test with 1.0.0-7 (already uploaded into github)

Thanks,
Baze
