### ISSUE TITLE
PUT & GET fail when memcache is down

### ISSUE THREAD

**Issue by sumantmanda** [GiorgioRegni/mod_encrypt#19]
Not sure if its a critical bug, but my understanding is that PUT and GET shouldn't fail. NO Matter What

When /etc/init.d/memcached is shutdown. All Put and Get fail.

restapi log

20151210 20:12:54.034 restapi id=0xc558250 context="generic" cmd="postreadreq" src="10.200.107.201" step="REQ_ERR" method="GET" uri="/" status="error" code="403" elapsed="0ms"
20151210 20:12:54.034 restapi id=0xc558250 context="generic" cmd="finished" src="10.200.107.201" step="REQ_END" method="GET" uri="/" code="403" elapsed="0ms" input_size="0bytes" output_size="101bytes"
20151210 20:13:54.921 restapi id=0xc374d70 context="generic" cmd="postreadreq" src="10.200.107.201" step="REQ_START" method="GET" uri="/menu"
20151210 20:13:54.921 restapi id=0xc374d70 context="bws" src="10.200.107.201" action="BWS_GET_LISTALLMYBUCKETS" userid="65A011A29CDF8EC533EC3D1CCAAE921C" username="Anonymous" check="NOGUEST" code="403" reason="AccessDenied"
20151210 20:13:54.921 restapi id=0xc374d70 context="generic" cmd="postreadreq" src="10.200.107.201" step="REQ_ERR" method="GET" uri="/" status="error" code="403" elapsed="0ms"
20151210 20:13:54.921 restapi id=0xc374d70 context="generic" cmd="finished" src="10.200.107.201" step="REQ_END" method="GET" uri="/" code="403" elapsed="0ms" input_size="0bytes" output_size="101bytes"
20151210 20:13:55.012 restapi id=0xc374d70 context="generic" cmd="postreadreq" src="10.200.107.201" step="REQ_START" method="GET" uri="/menu"
20151210 20:13:55.012 restapi id=0xc374d70 context="bws" src="10.200.107.201" action="BWS_GET_LISTALLMYBUCKETS" userid="65A011A29CDF8EC533EC3D1CCAAE921C" username="Anonymous" check="NOGUEST" code="403" reason="AccessDenied"
20151210 20:13:55.012 restapi id=0xc374d70 context="generic" cmd="postreadreq" src="10.200.107.201" step="REQ_ERR" method="GET" uri="/" status="error" code="403" elapsed="0ms"
20151210 20:13:55.012 restapi id=0xc374d70 context="generic" cmd="finished" src="10.200.107.201" step="REQ_END" method="GET" uri="/" code="403" elapsed="0ms" input_size="0bytes" output_size="101bytes"

**Comment by dmgrimal** [comment]
Memcached is a dependency of the product.  If it is not running, we would expect these 500 error codes to come up.  This should be expected behavior and this can be closed.

**Comment by GiorgioRegni** [comment]
Agreed with @sumantmanda this is the expected behavior.
