### ISSUE TITLE
The current master key and data encryption key must always be in memcached and retrieved from there

### ISSUE THREAD

**Issue by dmgrimal** [GiorgioRegni/mod_encrypt#2]
When apache starts up, if either the encryption or decryption is enabled,

<code>
FastCgiEncrypt On
</code>

or

<code>
FastCgiDecrypt On
</code>

then the module should retrieve the current master and data encryption keys from the key server(s).  These should be in memcached and used until the keys expire.   There should be no need to retrieve these keys if they are in memcached.

When the keys expire, the expired keys should be used until the new keys are retrieved.  If the call to retrieve the keys fails, the module should start responding with 503 calls indicating there is a problem.

**Comment by dmgrimal** [comment]
Also, if the key server is not available and the keys cannot be retrieved, the mod_encrypt should retry every 30 seconds (configurable option) to retrieve the keys.  

If a key expires and cannot be retrieved, then the same 503 errors should be returned until the key can be satisfied.

**Comment by BazeIlijoskki** [comment]
--------------------------
This is the list from the customer.
5. If active keys can not be retrieved then do not store unencrypted. Appropriate 4xx error MUST be returned
This means that it not store the unencrypted data, if the key server is not available.
And, return 4xx error.
----------------------
What`s the new specification?

**Comment by dmgrimal** [comment]
I am getting confirmation.  I am not sure I like "404" since it means "not found".  412 or 502 may be more appropriate.  Or even 415.

**Comment by BazeIlijoskki** [comment]
Fixed
