### ISSUE TITLE
A GET that needs to be decrypted should look for keys in memcached before querying key server

### ISSUE THREAD

**Issue by dmgrimal** [GiorgioRegni/mod_encrypt#4]
If an object that is retrieved upon a GET has a data encryption key that is in memcached, the mod_encrypt module must use the cached copy and not retrieve it from the key server.  The logic is that users will be putting backups of many objects at once into the system.  If they are retrieving them, most likely it will have used the same data encryption and master key.  This is why the object user metadata should have the master and data encryption key ids.

**Comment by BazeIlijoskki** [comment]
Implemented like this.
