### ISSUE TITLE
Parameters for mod_encrypt should be able to be defined in a <VirtualHost>

### ISSUE THREAD

**Issue by dmgrimal** [GiorgioRegni/mod_encrypt#6]
When configuring the mod_encrypt parameters, we ran into a problem where the parameters could not be defined in a VirtualHost.  Since we are configuring multipled FastCGI services on one server, we need to be able to support VirtualHosts and specific parameters per virtual host.  

This is the error we were getting. 

```
[root@lts2node2 conf.d]# service httpd restart
Stopping httpd:                                            [  OK  ]
Starting httpd: Syntax error on line 20 of /etc/httpd/conf.d/scality-sd.conf:
FastCgiEncrypt cannot occur within <VirtualHost> section
                                                           [FAILED]
```

**Comment by BazeIlijoskki** [comment]
Fixed
