### ISSUE TITLE
mod_encrypt breaks on Multi-Part-Uploads

### ISSUE THREAD

**Issue by mastachand** [GiorgioRegni/mod_encrypt#8]
Hey,

There is an issue when RS2 sends multi-part uploads. Without mod_encrypt, it works fine; with it, the first part upload ends up with a 400 (Bad Request) request.

Here's how to reproduce the issue.

Disable mod_decrypt:

log in to conn-1 and type the following sequence:

[root@conn-1 ~]# ringsh -R DATA
[...]
ring> use rs2
ring> accessor configSet msgstore_protocol_restapi bwsdrvdataopts sproxyd_srv=10.132.90.19:81;sproxyd_uri_arc=/proxy/arc;sproxyd_uri_chord=/proxy/chord

then launch this command:

[root@conn-1 ~]# s3cmd put /var/log/btmp s3://bucket/btmp
/var/log/btmp -> s3://bucket/btmp  [part 1 of 3, 15MB]
 15728640 of 15728640   100% in    7s     2.13 MB/s  done
/var/log/btmp -> s3://bucket/btmp  [part 2 of 3, 15MB]
 15728640 of 15728640   100% in    1s    12.79 MB/s  done
/var/log/btmp -> s3://bucket/btmp  [part 3 of 3, 6MB]
 7004544 of 7004544   100% in    3s  1721.50 kB/s  done

Success and getting the file works:

[root@conn-1 ~]# s3cmd get s3://bucket/btmp
s3://bucket/btmp -> ./btmp  [1 of 1]
 38461824 of 38461824   100% in    2s    15.45 MB/s  done
[root@conn-1 ~]# md5sum btmp /var/log/btmp
4d69b33bcf34bcd32609ea7738b2a8f1  btmp
4d69b33bcf34bcd32609ea7738b2a8f1  /var/log/btmp

enable mod_encrypt:

still on conn-1 and type the following sequence:

[root@conn-1 ~]# ringsh -R DATA
[...]
ring> use rs2
ring> accessor configSet msgstore_protocol_restapi bwsdrvdataopts sproxyd_srv=10.132.90.19:81;sproxyd_uri_arc=/encrypt/arc;sproxyd_uri_chord=/proxy/chord

Try the upload again:

[root@conn-1 ~]# s3cmd put /var/log/btmp s3://bucket/btmp
/var/log/btmp -> s3://bucket/btmp  [part 1 of 3, 15MB]
 15728640 of 15728640   100% in    1s    13.12 MB/s  done
WARNING: Upload failed: /btmp?partNumber=1&uploadId=916399417C695F7FE803B13CF2F85E4FE3BE2720 (500 (InternalError): None)
WARNING: Waiting 3 sec...

This gives an error directly at the first part. It says 500 Internal error at the s3cmd level. Sniffing the traffic, this is what we get back from mod_encrypt:

T 10.132.60.144:40905 -> 10.132.90.19:81 [AP]
PUT /encrypt/arc/1700D23BAB91D3311F253F3F78DB464AB9E49420 HTTP/1.0.
x-scal-split-policy: raw.
x-scal-usermd: QlotTUQDUzAwMDhtZXRhZGF0YQpWMDAwM2tleVQwMDAwMDAwMDAwMDRidG1wClYwMDA2YnVja2V0VDAwMDAwMDAwMDAwNmJ1Y2tldApWMDAwNW10aW1lSTE0NDUwMzQzMDUKVjAwMDRldGFnVDAwMDAwMDAwMDAzMmVhZGRmNGFlZWNjYmEwMTY0ODE3N2IzMWQ5YTcyNTRkClYwMDA0c2l6ZUwxNTcyODY0MApWMDAwM2FjbFIwMDAwMDAwMDA1MDNCV1MtQUNMAlMwMDA4UkVTVCBBQ1AKQjAwMDVPd25lcgpBMDAwNlVzZXJJRFQwMDAwM

[.... DATA ... ]

############################################################
T 10.132.90.19:81 -> 10.132.60.144:41320 [AP]
HTTP/1.1 400 Bad Request.
Date: Fri, 16 Oct 2015 22:59:12 GMT.
Server: Apache/2.2.15 (CentOS).
Content-Length: 146.
Connection: close.
Content-Type: text/html; charset=UTF-8.
.
<html><head><title>400 - Bad Request</title></head><body><h1>400 - Bad Request</h1><h2>EOF encountered on input with error -2</h2></body></html>.
Status: 400.
Content-Type: text/html.
Content-Length: 162.
.
<html><head><title>400 - Bad Request</title></head

There might be some understanding of how RS2 handles Multi Part Upload to solve this one, so please ping me here or by email (m@scality.com)

**Comment by BazeIlijoskki** [comment]
In the old code of mod_encrypt, there was a bug in processing the big file. (>1Mbytes)
The old code were installed over node-1.
This bug is already fixed.
