### ISSUE TITLE
log sanitization

### ISSUE THREAD

**Issue by mastachand** [GiorgioRegni/mod_encrypt#9]
Hey,

Would it be possible to sanitize logs and make sure they are all in mod_encrypt logs and not in apache logs. For example, the logs for each operation is done in apache error logs:

in fcgi_protocol.c:390
  ap_log_error(FCGI_LOG_WARN_NOERRNO, fcgi_apache_main_server,
        "FastCGIENC: %s %s %s auth %s", remote, method, uri, auth);

It would be good to have this in the mod_encrypt logs and maybe with more structure to them. Is there a way to sanitize this?

Thanks

**Comment by BazeIlijoskki** [comment]
Sure. It`s possible.
I will update like this.

**Comment by mastachand** [comment]
Thanks!

**Comment by BazeIlijoskki** [comment]
Implemented.
